# Generated by Django 4.2.16 on 2025-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default="images/default_profile.png", upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
