# Generated by Django 4.2.16 on 2025-05-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_img_alter_user_age_alter_user_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="e_mail",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_img",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
