# Generated by Django 4.2.16 on 2025-05-26 04:21
# Generated by Django 4.2.16 on 2025-05-26 00:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precious_metals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metalprice',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='metal_type',
            field=models.CharField(choices=[('GOLD', '금'), ('SILVER', '은')], max_length=10),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalprice',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
