# Generated by Django 4.2.16 on 2025-05-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("precious_metals", "0002_alter_metalprice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metalprice",
            name="close_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="metalprice",
            name="high_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="metalprice",
            name="low_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="metalprice",
            name="open_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="metalprice",
            name="volume",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
