# Generated by Django 4.2.16 on 2025-05-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepositProduct",
            fields=[
                (
                    "deposit_ID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("예금", "예금"), ("적금", "적금")], max_length=10
                    ),
                ),
                ("dcls_month", models.CharField(max_length=6)),
                ("fin_co_no", models.CharField(max_length=20)),
                ("kor_co_nm", models.CharField(max_length=100)),
                ("fin_prdt_nm", models.CharField(max_length=100)),
                ("join_way", models.CharField(blank=True, max_length=100)),
                ("mtrt_int", models.CharField(blank=True, max_length=100)),
                ("spcl_cnd", models.CharField(blank=True, max_length=200)),
                ("join_deny", models.CharField(blank=True, max_length=10)),
                ("join_member", models.CharField(blank=True, max_length=200)),
                ("etc_note", models.TextField(blank=True)),
                (
                    "max_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("dcls_strt_day", models.CharField(blank=True, max_length=20)),
                ("dcls_end_day", models.CharField(blank=True, max_length=20)),
                ("fin_co_subm_day", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DepositOption",
            fields=[
                (
                    "depositoption_ID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("intr_rate_type", models.CharField(max_length=10)),
                ("intr_rate_type_nm", models.CharField(max_length=50)),
                ("rsrv_type", models.CharField(blank=True, max_length=10)),
                ("rsrv_type_nm", models.CharField(blank=True, max_length=50)),
                ("save_trm", models.CharField(max_length=10)),
                (
                    "intr_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "intr_rate2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "deposit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="deposits.depositproduct",
                    ),
                ),
            ],
        ),
    ]
