# Generated by Django 4.2.16 on 2025-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='price_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
