# Generated by Django 4.2.16 on 2025-05-26 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crawlings", "0002_stockdata_price_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStockInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("stock_code", models.CharField(max_length=10)),
                (
                    "last_price",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interested_stocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_searched"],
                "unique_together": {("user", "stock_code")},
            },
        ),
    ]
